---

- name: Extract files
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: Start the web server
  become: true
  shell: |
    pm2 stop default
    pm2 start npm -- start

- name: "update apt package."
  become: yes
  apt:
    update_cache: yes
 
- name: "update packages"
  become: yes
  apt:
    upgrade: yes
    
- name: "Remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes   
   
    
- name: "Install Dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Start the web server
  become: true
  shell: |
    pm2 stop default
    pm2 start npm -- start
